waypoint_tools:
  ros__parameters:
    # Edit target YAML. Used only by waypoint_edit.launch.py.
    edit_waypoint_yaml_path: /home/takumi/ros2_ws/src/orne-box/orne_box_navigation_executor/config/waypoints/tsudanuma2-3.yaml

    # Send target YAMLs. Used only by waypoint_send.launch.py.
    send_waypoint_yaml_paths:
      - /home/takumi/ros2_ws/src/orne-box/orne_box_navigation_executor/config/waypoints/2-3_1.yaml
      - /home/takumi/ros2_ws/src/orne-box/orne_box_navigation_executor/config/waypoints/2-3_2.yaml

    # Output/edit mode: auto, waypoint_manager2, or waypoint_follower.
    edit_format: auto

    # Map and RViz files used by the editor launch.
    map_yaml_path: /home/takumi/ros2_ws/src/orne-box/orne_box_navigation_executor/config/maps/tsudanuma/tsudanuma_keepout.yaml
    # map_yaml_path: /home/takumi/ros2_ws/src/orne-box/orne_box_navigation_executor/config/maps/tsudanuma/cit_3f_map.yaml
    rviz_config_path: /home/takumi/ros2_ws/src/waypoint_tools/config/rviz/waypoint_tools.rviz

    # Common ROS settings.
    frame_id: map
    use_sim_time: false

    # Edit launch options.
    start_map: true
    start_rviz: true

    # Send launch options.
    action_name: /follow_waypoints
    send_on_start: true
